<template>
  <CCol>
    <CModal title="Confirm" color="info" :show.sync="recreateUsersModal">
      <div slot="default">
        <CRow>
          <CCol>
            Are you sure you want to perform this action? It cannot be reversed.
          </CCol>
        </CRow>
      </div>
      <div slot="footer">
        <CRow>
          <CCol>
            <CButton color="secondary" v-on:click="recreateUsersModal = false">
              Close
            </CButton>
          </CCol>
          <CCol>
            <CButton color="primary" v-on:click="recreateUsers">
              Confirm
            </CButton>
          </CCol>
        </CRow>
      </div>
    </CModal>

    <!-- ERROR TOASTER -->
    <CToaster :autohide="3000">
      <template v-for="toast in errorToasts">
        <CToast
          :key="'toast' + toast"
          :show="true"
          header="An error occured..."
        >
          {{ errorMessage }}
        </CToast>
      </template>
    </CToaster>

    <!-- SUCCESS TOASTER -->
    <CToaster :autohide="3000">
      <template v-for="toast in successToasts">
        <CToast :key="'toast' + toast" :show="true" header="Success!">
          {{ successMessage }}
        </CToast>
      </template>
    </CToaster>

    <CCard>
      <CCardHeader>
        Settings and Configuration
      </CCardHeader>
      <CCardBody>
        <CCol>
          <CRow class="m-2">
            <CCol>
              <CRow>
                <CCol>
                  <h5>Recreate missing users from authentication server</h5>
                </CCol>
              </CRow>
              <CRow>
                <CCol>
                  Recreates users which are present in the project's Firebase
                  authentication system and are missing from the application's
                  local database.
                </CCol>
              </CRow>
            </CCol>
            <CCol>
              <CButton
                color="info"
                size="lg"
                v-on:click="recreateUsersModal = true"
              >
                Recreate
              </CButton>
            </CCol>
          </CRow>
          <CRow class="m-2">
            <CCol>
              <CRow>
                <CCol>
                  <h5>Clear user-generated content</h5>
                </CCol>
              </CRow>
              <CRow>
                <CCol>
                  Clears the database from in-app questionnaire responses and
                  notification questionnaire responses generated by users.
                </CCol>
              </CRow>
            </CCol>
            <CCol>
              <CButton color="info" size="lg">
                Clear
              </CButton>
            </CCol>
          </CRow>
        </CCol>
      </CCardBody>
    </CCard>
  </CCol>
</template>

<script>
import RecreateUsersMutation from "../../graphql/mutations/RECREATE_USERS.gql";
export default {
  name: "Settings",
  data() {
    return {
      errorToasts: 0,
      successToasts: 0,
      successMessage: "",
      errorMessage: "",
      recreateUsersModal: false,
    };
  },
  methods: {
    recreateUsers() {
      const _this = this;
      this.$apollo
        .mutate({
          mutation: RecreateUsersMutation,
        })
        .then(function(data) {
          let message = "";
          if (data.recreateUsers && data.recreateUsers > 0) {
            message = `Sucessfully recreated ${data.recreateUsers} users.`;
          } else {
            message = `Found no users to recreate.`;
          }
          _this.successMessage = message;
          _this.successToasts = _this.successToasts + 1;
          _this.recreateUsersModal = false;
        })
        .catch(function(error) {
          const message = "An error occured: " + error;
          _this.errorMessage = message;
          _this.errorToasts = _this.errorToasts + 1;
          _this.recreateUsersModal = false;
        });
    },
  },
};
</script>
