
import gql from "graphql-tag"

export default gql`
    query DocumentsList($ownerId: ID!) {
    documentsByOwner(ownerId: $ownerId){
        _id
        ownerId
        filename
        length
        md5
        uploadDate
    }
}
`