import gql from "graphql-tag"

export default gql`
    query IconsByName($filenames: [String]) {
        iconsByName(filenames: $filenames) {
            _id
            filename
            length
            uploadDate
            md5
            data
        }
    }
`