
import gql from "graphql-tag"

export default gql`
    query InAppQuestionnaires {
        inAppQuestionnaires {
            _id
            name
            isArchived
            creationDate
            description
        }
    }
`