
import gql from "graphql-tag"

export default gql`
    query LatestInAppQuestionnaireContent($questionnaireId: ID) {
        latestInAppQuestionnaireContent(questionnaireId: $questionnaireId){
            _id
            creationDate
            multipleChoiceItems {
                _id
                index
                question
                choices {
                    display
                    value
                    type
                }
            }
            freeTextItems {
                index
                question
            }
        }
    }
`