
import gql from "graphql-tag"

export default gql`
    query Nodes($nqId: ID){
        nodes(nqId:$nqId){
            _id
            nqId
            nodeLabel
            isSourceNode
            isArchived
            position {
                xPos
                yPos
            }
            data {
                nqId
                type
                question {
                    timeOfDay {
                        minute
                        hour
                    }
                    visible
                    questionText
                    questionChoices {
                        choiceIconMd5
                        choiceIconId
                        choiceIcon
                        choiceValueType
                        choiceValue
                    }
                }
                appquestionnaire {
                    qid
                    customTitle
                    customBody
                    timeOfDay {
                        minute
                        hour
                    }
                }
            }
        }
}
`