import gql from "graphql-tag"

export default gql`
    query NotificationQuestionnaires {
        notificationQuestionnaires {
            _id
            name
            description
            created
            isActive
            isArchived
            lastModified
        }
    }
`