import gql from "graphql-tag"

export default gql`
    query NotificationQuestionnaireResponses {
        notificationQuestionnaireResponses {
            _id
            timestamp
            user {
                _id
                email
            }
            notificationQuestionnaire {
                _id
                name
            }
            previous
            next
            nodeId
            responseData {
                questionText
                choices {
                    choiceIcon
                    choiceValueType
                    choiceValue
                }
                selectedChoice {
                    choiceIcon
                    choiceValueType
                    choiceValue
                }
            }
        }
    }
`