
import gql from "graphql-tag"

export default gql`
    query NotificationResponsesPerDay($startDate: Date, $endDate: Date) {
        numberOfResponsesForEachDay(
            startDate: $startDate
            endDate: $endDate
        )
    }
`
