import gql from "graphql-tag"

export default gql`
    query Users {
        users {
            _id
            age
            email
            lastName
            firstName
            profileImage
            creationDate
            fcmRegistrationToken
            notificationsEnabled
        }
    }
`