import gql from "graphql-tag"

export default gql`
    query User($_id: ID!) {
        user(_id: $_id){
            _id
            firstName
            lastName
            age
            fcmRegistrationToken
            notificationsEnabled
            profileImage
            creationDate
            email
        }
    }
`